name: shell commands
on: [push]

jobs:
  run-shell-command:
    runs-on: ubuntu-latest
    steps:
      - name: echo
        run: echo "How are you Memo"
      - name: version
        run: |
          node -v
          npm -v
      - name: python 
        run: |
          import platform
          print(platform.processor())
        shell: python